version: 1.0.{build}

environment:
  VisualStudioVersion: 12.0

branches:
  only:
  - appveyor

platform:
  - Win32

install:
  - ps: $env:gitrev=git describe --tags
  - ps: Update-AppveyorBuild -Version "$env:gitrev-$env:appveyor_repo_branch-$env:appveyor_build_number"

build_script:
  - msbuild buildbot.xml /m /t:ReleaseAll

after_build:
  - type NUL > bin\portable.ini
  - set FOLDER_NAME=pcsx2-%gitrev%-windows-x86
  - rename bin %FOLDER_NAME%
  - 7z a -mx9 %FOLDER_NAME%.7z %FOLDER_NAME%

test: off

artifacts:
  - path: $(FOLDER_NAME).7z
    name: $(FOLDER_NAME)
